<!doctype html>
<html lang="en">

<head>
   <?php
   $title = "Terms of Service - bitcoin data.science";
   $description = "Terms of Service and disclaimers for using bitcoin data.science and its analytical tools.";
   $canonical = "https://bitcoindata.science/terms-of-service";
   include_once $_SERVER['DOCUMENT_ROOT'] . '/components/head.php';
   ?>
</head>

<body>
   <!-- Navbar -->
   <header>
      <navbar-component></navbar-component>
   </header>

   <!-- Page Content -->
   <?php
   $h1 = 'Terms of Service';
   $h2 = 'Please read these terms carefully before using our tools and services.';
   $showAd = false;
   include_once $_SERVER['DOCUMENT_ROOT'] . '/components/page-header.php';
   ?>

   <div class="bg-body-tertiary rounded-4 p-md-5 p-4 shadow-sm mb-5">
      <div class="row">
         <div class="col-12 col-lg-10 mx-auto">

            <section class="mb-5">
               <h3 class="h4 text-primary fw-bold mb-3">1. Agreement to Terms</h3>
               <p>By accessing or using <a href="https://bitcoindata.science">bitcoindata.science</a> (the "Website") and any of its tools, calculators, or bots, you agree to be bound by these Terms of Service. If you do not agree to all of these terms, you are prohibited from using the Website and must discontinue use immediately.</p>
            </section>

            <section class="mb-5">
               <h3 class="h4 text-primary fw-bold mb-3">2. Bitcoin Address Balance Checker</h3>
               <p>The Balance Checker is a client-side tool designed to query the balance of public Bitcoin addresses.</p>
               <ul>
                  <li><strong>Data Processing:</strong> All address inputs are processed locally on your browser. We never request, access, or store your addresses.</li>
                  <li><strong>Third-Party APIs:</strong> To fetch address balances, the tool queries public block explorer APIs (including Blockchain.info, Mempool.space, and Blockchair). By using the balance checker, your public address information is shared with these third-party providers. We are not responsible for their terms of service, uptime, or privacy practices.</li>
                  <li><strong>Live Updates:</strong> If enabled, the page automatically refreshes at designated intervals (every 20 minutes for 20 or fewer addresses). We do not guarantee the real-time accuracy or uninterrupted service of these updates.</li>
               </ul>
            </section>

            <section class="mb-5">
               <h3 class="h4 text-primary fw-bold mb-3">3. Bitcoin Giveaway Manager</h3>
               <p>The Giveaway Manager is a utility tool that facilitates provably fair winner selection based on the Bitcoin blockchain.</p>
               <ul>
                  <li><strong>Provably Fair Mechanism:</strong> The tool uses the cryptographic hash of a specified future Bitcoin block to randomly seed the drawing. This selection process is verifiable by anyone.</li>
                  <li><strong>Role of the Platform:</strong> We provide this tool solely as a utility for giveaway organizers and participants. We do not host, sponsor, administer, or endorse any giveaways run using this tool. </li>
                  <li><strong>Liability:</strong> We accept no liability for disputes, manipulation by hosts, failure of hosts to distribute prizes, or any technical errors in blockhash retrieval.</li>
               </ul>
            </section>

            <section class="mb-5">
               <h3 class="h4 text-primary fw-bold mb-3">4. Altcoinstalks Notification Bot</h3>
               <p>The Notification Bot tracks forum mentions and quotes on the Altcoinstalks forum.</p>
               <ul>
                  <li><strong>Independence:</strong> This bot is an independent utility and is not officially affiliated with, endorsed by, or in partnership with the Altcoinstalks forum administration.</li>
                  <li><strong>Usernames & Security:</strong> Users register for notifications by providing their public forum username. We never ask for, nor should you ever provide, passwords or private forum credentials.</li>
                  <li><strong>Data Storage:</strong> Collected notification snippets (mentions and quotes) are not stored on our servers, and they are always fetched from Altcoinstalks forum. Read statuses and tracked notifications are saved client-side in your browser's local storage.</li>
               </ul>
            </section>

            <section class="mb-5">
               <h3 class="h4 text-primary fw-bold mb-3">5. JJG Sustainable Withdrawal Strategy</h3>
               <p>The JJG Withdrawal Strategy is a simulation model that calculates potential monthly budget limits relative to the 200-Week Moving Average (200-WMA).</p>
               <ul>
                  <li><strong>NOT FINANCIAL ADVICE:</strong> All simulations, charts, and values generated by this calculator are for educational and informational purposes only. They do not constitute investment, financial, tax, or legal advice.</li>
                  <li><strong>Accuracy of Data:</strong> The tool relies on historical price feeds and public market APIs. While we make efforts to keep this data current, we do not warrant the accuracy, completeness, or timeliness of the calculations or market prices.</li>
                  <li><strong>Risk Disclaimer:</strong> Bitcoin is highly volatile. Any investment or withdrawal strategy carries a high risk of loss. You are solely responsible for any decisions you make based on this tool.</li>
               </ul>
            </section>

            <section class="mb-5">
               <h3 class="h4 text-primary fw-bold mb-3">6. General Disclaimer of Warranties</h3>
               <p>The Website and all its tools are provided on an <strong>"AS IS"</strong> and <strong>"AS AVAILABLE"</strong> basis. We make no warranties, expressed or implied, regarding the accuracy, completeness, reliability, or availability of the website or the services provided.</p>
            </section>

            <section class="mb-5">
               <h3 class="h4 text-primary fw-bold mb-3">7. Limitation of Liability</h3>
               <p>In no event shall <a href="https://bitcoindata.science">bitcoindata.science</a>, its developers, or contributors be liable for any direct, indirect, incidental, special, or consequential damages (including, but not limited to, financial losses, loss of profits, loss of data, or bot notification delays) arising out of the use or inability to use the tools provided on this website.</p>
            </section>

            <section class="mb-5">
               <h3 class="h4 text-primary fw-bold mb-3">8. Modifications to Terms</h3>
               <p>We reserve the right to update or modify these Terms of Service at any time without prior notice. Your continued use of the Website after any changes constitutes acceptance of the new terms.</p>
            </section>

            <div class="text-muted small mt-4 pt-3 border-top">
               Last Updated: July 13, 2026
            </div>

         </div>
      </div>
   </div>

   </main>

   <footer-component></footer-component>
</body>

</html>