name: Deploy to DirectAdmin via FTP

on:
  push:
    branches:
      - main
      
jobs:
  web-deploy:
    name: Deploy to DirectAdmin via FTP
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.6
      with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          server-dir: /public_html/
